spring.application.name=api-prodify
server.port=8080
server.address=0.0.0.0
# ===============================================================================
# CONFIGURAÇÕES DE BANCO DE DADOS
# ===============================================================================
spring.datasource.url=jdbc:postgresql://localhost:5432/transenior
spring.datasource.username=postgres
spring.datasource.password=@@m159753123R@@
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# Em desenvolvimento, permitir que o Hibernate atualize/ crie tabelas automaticamente
spring.jpa.hibernate.ddl-auto=update

# ===============================================================================